name: Android Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # DEBUG: This will show us where you put the files
    - name: List Files (Debug)
      run: |
        echo "CURRENT DIRECTORY CONTENTS:"
        ls -la
        echo "---------------------------"
        echo "CHECKING FOR BUILD.GRADLE:"
        if [ -f "build.gradle" ]; then echo "✅ Found build.gradle at root"; else echo "❌ MISSING build.gradle at root"; fi
        if [ -d "app" ]; then echo "✅ Found app folder at root"; else echo "❌ MISSING app folder at root"; fi

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # This installs Gradle 8.0 directly
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.0'

    # Using explicit ':app:assembleDebug' to target the app module
    - name: Build with Gradle
      run: gradle :app:assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
